### ISSUE TITLE
Version 1.7.1 — unable to start sidekiq

### ISSUE THREAD

**Issue by kigster** [vinted/sidekiq-pool#26]
On Ruby 2.2.7, Ubuntu 16.04, we are seeing the following with 1.7.1. 

```
❯ be sidekiq-pool -C config/sidekiq-pool.yml
2018-06-12T18:48:12.281Z 31042 TID-ow2lr5o32 INFO: Starting new pool
2018-06-12T18:48:41.725Z 31042 TID-ow2lr5o32 INFO: Adding child with args: (-g homebase.default -q default,10 -q critical,20 -q low,1 -c 10) in , waiting for busy: true
2018-06-12T18:48:41.729Z 31042 TID-ow2lr5o32 INFO: Waiting for child 31234 to be busy break in 29
/Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:280:in `run_after_fork_hooks': undefined method `after_fork_hooks' for Sidekiq::Pool:Module (NoMethodError)
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:214:in `block in fork_child'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:199:in `fork'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:199:in `fork_child'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:75:in `block (2 levels) in start_new_pool'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:73:in `times'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:73:in `block in start_new_pool'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:72:in `each'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:72:in `start_new_pool'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:28:in `run'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/bin/sidekiq-pool:10:in `<top (required)>'
	from /Users/kig/.rbenv/versions/2.2.7/bin/sidekiq-pool:23:in `load'
	from /Users/kig/.rbenv/versions/2.2.7/bin/sidekiq-pool:23:in `<top (required)>'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
	from /Users/kig/.rbenv/versions/2.2.7/bin/bundle:23:in `load'
	from /Users/kig/.rbenv/versions/2.2.7/bin/bundle:23:in `<main>'
```

As a result, sidekiq-pool comes up, but sidekiq processes keep dying and respawning indefinitely.

After looking into this error, it appears that the method `run_after_fork_hooks` has been added into `lib/sidekiq/pool.rb` with 1.7.1. but `pool.rb` is not required from `lib/sidekiq/pool/cli.rb` (which is the only file required by the executable). 

After adding a missing reqiure to `cli.rb`, I got another error: 

```
2018-06-12T18:53:04.541Z 33281 TID-owdrdtn59 INFO: Waiting for child 33467 to be busy break in 29
/Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:281:in `run_after_fork_hooks': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:215:in `block in fork_child'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:200:in `fork'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:200:in `fork_child'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:76:in `block (2 levels) in start_new_pool'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:74:in `times'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:74:in `block in start_new_pool'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:73:in `each'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:73:in `start_new_pool'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/lib/sidekiq/pool/cli.rb:29:in `run'
	from /Users/kig/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/sidekiq-pool-1.7.1/bin/sidekiq-pool:10:in `<top (required)>
```

And this is when I gave up, and reverted to 1.7.0 that works like a charm.

Thanks!

**Comment by laurynas** [comment]
@kigster thank you for the report. Added a [fix](https://github.com/vinted/sidekiq-pool/pull/28) and releases `1.7.2` version.

**Comment by kigster** [comment]
👍🏽
