### ISSUE TITLE
Running into Error when launching Sidekiq-Pool

### ISSUE THREAD

**Issue by JohnLegrandRichards** [vinted/sidekiq-pool#49]
bundle exec sidekiq-pool
super: no superclass method `write_pid' for #<Sidekiq::Pool::CLI:0x00007f8dc7c0d468>
/Users/johnrichards/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/sidekiq-pool-2.0.0/lib/sidekiq/pool/cli.rb:23:in `write_pid'
/Users/johnrichards/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/sidekiq-pool-2.0.0/lib/sidekiq/pool/cli.rb:28:in `run'
/Users/johnrichards/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/sidekiq-pool-2.0.0/bin/sidekiq-pool:10:in `<top (required)>'
/Users/johnrichards/.rvm/rubies/ruby-2.7.4/bin/sidekiq-pool:23:in `load'
/Users/johnrichards/.rvm/rubies/ruby-2.7.4/bin/sidekiq-pool:23:in `<main>'
/Users/johnrichards/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
/Users/johnrichards/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'

**Comment by viraptor** [comment]
Running into the same issue - could you update for the new sidekiq interface @laurynas? Thanks!
